// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRefToken = `-- name: AddRefToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, expires_at,revoked_at, user_id)
VALUES (
  $1,                         -- token
  NOW(),                      -- created_at
  NOW(),                      -- updated_at
  NOW() + interval '60 days', -- expires_at
  NULL,                       -- revoked_at
  $2                          -- user_id
)
RETURNING token, created_at, updated_at, expires_at, revoked_at, user_id
`

type AddRefTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) AddRefToken(ctx context.Context, arg AddRefTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, addRefToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}
